- name: Create and get certificate from the certificate manager
  delegate_to: localhost
  block:
  - name: Create certificate from the certificate manager
    kubernetes.core.k8s:
      state: present
      template: certificate.yml.j2

  - name: Read certificate secret
    delegate_to: localhost
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Secret
      name: "{{ proxy_certificate_name }}"
      namespace: "{{ proxy_certificate_namespace }}"
    register: proxy_certificate_secret

- name: Set Secret Data
  ansible.builtin.set_fact:
    proxy_certificate_secret_data: "{{ proxy_certificate_secret.resources[0] }}"
