- name: Install the required packages
  ansible.builtin.dnf:
    name: podman
    state: present
  async: 1800
  poll: 10

- name: Enable lingering for ansible_user
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ ansible_user_id }}
    creates: '/var/lib/systemd/linger/{{ ansible_user_id }}'

- name: Add the ip_table module to allow using a Podman Network
  community.general.modprobe:
    name: ip_tables
    persistent: present
    state: present
