- name: Get Certificates secret data from files
  ansible.builtin.include_tasks:
    file: read_certs.yml
  when: not proxy_use_k8s_cert_manager

- name: Get Certificates secret data using K8S certificate manager
  ansible.builtin.include_tasks:
    file: cert_manager.yml
  when: proxy_use_k8s_cert_manager

- name: Create the podman kube secret for the proxy certificate
  containers.podman.podman_secret:
    name: "{{ proxy_certificate_name }}"
    state: present
    skip_existing: true
    data: "{{ proxy_certificate_secret_data }}"

- name: Create Quadlet directory
  ansible.builtin.file:
    path: "{{ proxy_quadlet_directory }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'

- name: Create Quadlet files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ proxy_quadlet_directory }}/{{ item }}"
    mode: '0644'
  loop:
  - proxy.kube
  - proxy.yml
  - proxy-config.yml

- name: Run daemon reload to make Quadlet create the service files
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: "Starting the proxy service"
  ansible.builtin.systemd_service:
    state: restarted
    scope: user
    name: proxy.service
  async: 1800
  poll: 10
