- name: Installations
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true

- name: Provision Ollama
  ansible.builtin.include_tasks:
    file: setup_ollama.yml
    apply:
      become: false
