- name: Define secret data structure
  ansible.builtin.set_fact:
    _ollama_certificate_secret_data:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ ollama_certificate_name }}"
      type: "kubernetes.io/tls"
      data:
        ca.crt: "{{ lookup('ansible.builtin.file', ollama_certificate_ca_file) | b64encode }}"
        tls.crt: "{{ lookup('ansible.builtin.file', ollama_certificate_cert_file) | b64encode }}"
        tls.key: "{{ lookup('ansible.builtin.file', ollama_certificate_key_file) | b64encode }}"

- name: Set secret data
  ansible.builtin.set_fact:
    ollama_certificate_secret_data: "{{ _ollama_certificate_secret_data | to_json }}"
