- name: Get Certificates secret data from files
  ansible.builtin.include_tasks:
    file: read_certs.yml
  when: not ollama_use_k8s_cert_manager

- name: Get Certificates secret data using K8S certificate manager
  ansible.builtin.include_tasks:
    file: cert_manager.yml
  when: ollama_use_k8s_cert_manager

- name: Create the podman kube secret for the ollama certificate
  containers.podman.podman_secret:
    name: "{{ ollama_certificate_name }}"
    state: present
    skip_existing: true
    data: "{{ ollama_certificate_secret_data }}"

- name: Add Proxy files and services
  ansible.builtin.set_fact:
    _ollama_template_files_list: "{{ _ollama_template_files_list + ['ollama-proxy.kube', 'ollama-proxy.yml', 'ollama-proxy-config.yml']}}"
    _ollama_services_list: "{{ _ollama_services_list + ['ollama-proxy'] }}"
