name: Jinja Lint
on:
- push
- pull_request
- workflow_call

jobs:
  jinja-lint:
    name: Jinja Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run jinja-lint
      uses: ansible-actions/j2lint-action@v0.0.1
      with:
        target: "*.j2"
